#define DRIVER_NAMEA		       	"FileDevIOCTLDemo"
#define DRIVER_NAMEW		       	L"FileDevIOCTLDemo"
#define DEV_TYPE					FILE_DEVICE_UNKNOWN

#define IOCTL_BUFFERED_WRITE	CTL_CODE(DEV_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DIRECT_WRITE		CTL_CODE(DEV_TYPE, 0x800, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_NEITHER_WRITE		CTL_CODE(DEV_TYPE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_BUFFERED_READ		CTL_CODE(DEV_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DIRECT_READ		CTL_CODE(DEV_TYPE, 0x801, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_NEITHER_READ		CTL_CODE(DEV_TYPE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IN_BUFFER_SIZE	0x100
#define OUT_BUFFER_SIZE	IN_BUFFER_SIZE

#if defined(_NTDDK_) || defined(_WDMDDK_)
	DECLARE_CONST_UNICODE_STRING(deviceName, L"\\Device\\"DRIVER_NAMEW);
	DECLARE_CONST_UNICODE_STRING(symbolicLinkName, L"\\??\\"DRIVER_NAMEW);
#else
	TCHAR	serviceName[]		= _TEXT(DRIVER_NAMEA);
	TCHAR	symbolicLinkName[]	= _TEXT("\\\\.\\")_TEXT(DRIVER_NAMEA);
	TCHAR	imageName[]			= _TEXT(DRIVER_NAMEA)_TEXT(".sys");
#endif

