#define DRIVER_NAMEA		       	"CMOSSetupBIOS"
#define DRIVER_NAMEW		       	L"CMOSSetupBIOS"
#define DEV_TYPE					FILE_DEVICE_UNKNOWN

#define IOCTL_GET_CURRENT_DATE_TIME	CTL_CODE(DEV_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_NEW_DATE_TIME		CTL_CODE(DEV_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_DIAGNOSTIC_STATUS	CTL_CODE(DEV_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_STATUS_REGISTER_D	CTL_CODE(DEV_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#if defined(_NTDDK_) || defined(_WDMDDK_)
	DECLARE_CONST_UNICODE_STRING(deviceName, L"\\Device\\"DRIVER_NAMEW);
	DECLARE_CONST_UNICODE_STRING(symbolicLinkName, L"\\??\\"DRIVER_NAMEW);
#else
	TCHAR	serviceName[]		= _TEXT(DRIVER_NAMEA);
	TCHAR	symbolicLinkName[]	= _TEXT("\\\\.\\")_TEXT(DRIVER_NAMEA);
	TCHAR	imageName[]			= _TEXT(DRIVER_NAMEA)_TEXT(".sys");
#endif

